"""add PKs

Revision ID: 16bfde3f7ac8
Revises: 5a0601bac538
Create Date: 2025-03-13 22:47:51.266125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bfde3f7ac8'
down_revision: Union[str, None] = '5a0601bac538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'id')
    # ### end Alembic commands ###
