"""delete image

Revision ID: 2fc7c312c15b
Revises: 83f28e5e013a
Create Date: 2025-03-13 01:36:28.664713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc7c312c15b'
down_revision: Union[str, None] = '83f28e5e013a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
