"""delete author

Revision ID: 6eae5ecb1d1a
Revises: 862114b2604f
Create Date: 2025-03-14 14:19:26.404802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eae5ecb1d1a'
down_revision: Union[str, None] = '862114b2604f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_nutrition')
    op.drop_table('authors')
    op.alter_column('recipe_ingredients', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('author_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'authors', ['author_id'], ['author_id'])
    op.alter_column('recipe_ingredients', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('authors',
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('recipe_nutrition',
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('calories', sa.INTEGER(), nullable=True),
    sa.Column('fat', sa.FLOAT(), nullable=True),
    sa.Column('protein', sa.FLOAT(), nullable=True),
    sa.Column('carbs', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    # ### end Alembic commands ###
