"""trial

Revision ID: 862114b2604f
Revises: 2e1138f224c6
Create Date: 2025-03-13 23:48:25.757407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862114b2604f'
down_revision: Union[str, None] = '2e1138f224c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('meal_type', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('cuisine', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('difficulty', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'difficulty')
    op.drop_column('recipes', 'cuisine')
    op.drop_column('recipes', 'meal_type')
    # ### end Alembic commands ###
